### ISSUE TITLE
Create Java Package

### ISSUE THREAD

**Issue by mghosh00** [mghosh00/BasicNeuralNetwork#9]
In order to make this package more flexible, I will create a Java package mimicking the existing Python one. Other benefits include:

* Reduced run time for simulations
* Practice in Java development and working with Gradle
* Better typing
* Opens up potential for multi-threading with different batches

**Comment by mghosh00** [comment]
## Task overview

- [ ] Re-organise file structure and create skeleton for new Java project with Gradle
- [ ] Update all workflows and create new ones for Java
- [ ] Write up all classes in Java (will have to explore plotting and dataframe methods)
- [ ] Use JUnitTest to unit test the new Java package
- [ ] Ensure all documentation is fully updated on readthedocs.io with Java classes
- [ ] Ensure that codecov reports are still being produced correctly and work with Java
